In [1]:
pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\admin\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: scikit-learn in c:\users\admin\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\admin\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\admin\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\admin\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [6]:
df['age'] = df['age'].fillna(df['age'].median())
df['city'] = df['city'].fillna(df['city'].mode()[0])

df = df.drop_duplicates()

df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

In [7]:
from sklearn.preprocessing import LabelEncoder

df = pd.get_dummies(df, columns=['city'])

le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2  35.0       0          80000        True        False
2            3  35.0       0          60000        True        False
3            4  35.0       1         120000       False         True
5            5  40.0       1          95000        True        False

In [8]:
from sklearn.preprocessing import MinMaxScaler

df_minmax = df.copy()

scaler = MinMaxScaler()
df_minmax[['age', 'annual_income']] = scaler.fit_transform(
    df_minmax[['age', 'annual_income']]
)

df_minmax

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000       False         True
1            2  0.666667       0         0.5000        True        False
2            3  0.666667       0         0.2500        True        False
3            4  0.666667       1         1.0000       False         True
5            5  1.000000       1         0.6875        True        False

In [9]:
from sklearn.preprocessing import StandardScaler

df_standard = df.copy()

scaler = StandardScaler()
df_standard[['age', 'annual_income']] = scaler.fit_transform(
    df_standard[['age', 'annual_income']]
)

df_standard

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.837117       1      -1.410970       False         True
1            2  0.204124       0       0.036179        True        False
2            3  0.204124       0      -0.687396        True        False
3            4  0.204124       1       1.483328       False         True
5            5  1.224745       1       0.578860        True        False

Min-Max Scaling scales data to a fixed range (0 to 1) and is useful when features need to be bounded, such as in neural networks or KNN.

Standardization transforms data to have mean 0 and standard deviation 1, making it suitable for algorithms like SVM and linear regression that assume normally distributed data.